Repository izpack/izpack, pull requests merged in 2018-03, with the labels that each got.

#676 Fixes IZPACK-1623 by replacing URLClassLoader.findResources
  izpack-core/src/main/java/com/izforge/izpack/merge/resolve/PathResolver.java
Labels: bug

#657 Fixing IZPACK-1469
  izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/GUIPackResources.java
Labels: bug

#665 Deleted useless import URLClassLoader
  izpack-installer/src/main/java/com/izforge/izpack/installer/unpacker/UnpackerBase.java
Labels: bug

#678 missing Italian translations
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/ita.xml
Labels: translation

#671 Update bra.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/bra.xml
Labels: translation

#672 IZPACK-1616: Fix exception if reg entry with REG_EXPAND_SZ is empty.
  izpack-api/src/main/java/com/izforge/izpack/api/config/spi/RegEscapeTool.java
  izpack-core/src/test/java/com/izforge/izpack/core/variable/RegistryValueTest.java
Labels: bug

#668 IZPACK-1593: reactivate GUI integration tests
  .travis.yml
  izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/UserInputPanelTest.java
  izpack-test/src/test/java/com/izforge/izpack/integration/InstallationTest.java
Labels: bug

#662 FIX capacity overflow when pack size exceeds int size
  izpack-panel/src/main/java/com/izforge/izpack/panels/packs/PacksModel.java
  izpack-panel/src/main/java/com/izforge/izpack/panels/treepacks/TreePacksConsolePanel.java
Labels: bug

#666 IZPACK-1603: fix NPE on ShortcutPanel when menu shortcut creation (checkbox) is disabled
  izpack-panel/src/main/java/com/izforge/izpack/panels/shortcut/ShortcutPanelLogic.java
Labels: bug

#667 IZPACK-1604: fix warning at shortcut creation
  izpack-dist/src/main/izpack/shortcutSpec.xml
Labels: bug

#670 IZPACK-1552: fix wrong property substitution for 'dir' and 'src' attributes
  izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
Labels: bug

#673 IZPACK-1618 : Use the correct inputStream when reading resource file
  izpack-event/src/main/java/com/izforge/izpack/event/AntActionUninstallerListener.java
Labels: bug

#680 Fixes IZPACK-1624 by computing intersection of OS constraint lists
  izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
  izpack-util/src/main/java/com/izforge/izpack/util/OsConstraintHelper.java
  izpack-util/src/test/java/com/izforge/izpack/util/OsConstraintHelperTest.java
Labels: enhancement

#675 Izpack 1620: Set SummaryPanel Next button text
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/bra.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/ces.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/deu.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/ell.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/eng.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/eus.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/fa.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/fin.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/fra.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/glg.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/hun.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/idn.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/ita.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/jpn.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/kor.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/nld.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/nor.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/pol.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/prt.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/rus.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/slk.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/spa.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/swe.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/twn.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/ukr.xml
  izpack-panel/src/main/java/com/izforge/izpack/panels/summary/SummaryPanel.java
Labels: enhancement

#677 Fixes Unix shortcut ownership and permissions when installing using sudo
  izpack-installer/src/main/java/com/izforge/izpack/util/os/Unix_Shortcut.java
Labels: bug
