Repository izpack/izpack, pull requests merged in 2020-03, with the labels that each got.

#705 IZPACK-1662 Fix by removing premature cast to Serializable
  izpack-installer/src/main/java/com/izforge/izpack/installer/data/UninstallDataWriter.java
  izpack-test/src/test/java/com/izforge/izpack/integration/UninstallDataWriterTest.java
Labels: bug

#702 IZPACK-1667 - Updating Commons Compress and Pdfbox
  pom.xml
Labels: bug

#711 IZPACK-1668: Fixed build failure on Win10 because of new registry entry types.
  izpack-api/src/main/java/com/izforge/izpack/api/config/Registry.java
  izpack-api/src/main/java/com/izforge/izpack/api/config/spi/AbstractParser.java
  izpack-api/src/main/java/com/izforge/izpack/api/config/spi/IniParser.java
  izpack-api/src/main/java/com/izforge/izpack/api/config/spi/OptionsParser.java
  izpack-api/src/main/java/com/izforge/izpack/api/config/spi/RegBuilder.java
  izpack-api/src/main/java/com/izforge/izpack/api/config/spi/RegEscapeTool.java
  izpack-util/src/test/java/com/izforge/izpack/api/config/spi/AbstractParserTest.java
  izpack-util/src/test/java/com/izforge/izpack/api/config/spi/IniParserTest.java
Labels: bug, izpack:build

#699 IZPACK-1655 - Allow exclude of properties that may contain passwords
  izpack-maven-plugin/src/main/java/org/izpack/mojo/IzPackNewMojo.java
Labels: enhancement
