Repository izpack/izpack, pull requests merged in 2020-08, with the labels that each got.

#717 IZPACK-1683 Fixes the initial value to honor custom true/false values
  izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/check/CheckField.java
  izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/console/check/ConsoleCheckFieldTest.java
  izpack-panel/src/test/resources/com/izforge/izpack/panels/userinput/check/userInputSpec.xml
Labels: bug

#718 IZPACK-1682 Adds additional GUI test
  izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/UserInputPanelTest.java
  izpack-panel/src/test/resources/com/izforge/izpack/panels/userinput/textarea/userInputSpec.xml
Labels: enhancement

#719 IZPACK-1684 fill all passwords in group if value is set on spec
  izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/gui/password/GUIPasswordGroupField.java
  izpack-panel/src/test/java/com/izforge/izpack/panels/userinput/UserInputPanelTest.java
  izpack-panel/src/test/resources/com/izforge/izpack/panels/userinput/password/userInputSpec.xml
Labels: bug, enhancement

#720 Issue: IZPACK-1656 fix file queue parameter
  izpack-installer/src/main/java/com/izforge/izpack/util/os/WinSetupFileQueue.java
Labels: bug
