Repository izpack/izpack, pull requests merged in 2021-11, with the labels that each got.

#748 [IZPACK-1642] The substitution does not work correctly on non-Latin encoding (VariableSubstitutorInputStream)
  izpack-core/src/main/java/com/izforge/izpack/core/substitutor/VariableSubstitutorInputStream.java
  izpack-core/src/test/java/com/izforge/izpack/core/substitutor/VariableSubstitutorInputStreamTest.java
Labels: bug

#752 [IZPACK-1706] Fixed execution of integration tests.
  izpack-maven-plugin/pom.xml
  izpack-maven-plugin/src/it/izpack-172/goals.txt
  izpack-maven-plugin/src/it/izpack-172/invoker.properties
  izpack-maven-plugin/src/it/izpack-172/pom.xml
  izpack-maven-plugin/src/it/izpack-172/validate.groovy
  izpack-maven-plugin/src/it/sample/goals.txt
  izpack-maven-plugin/src/it/sample/pom.xml
  izpack-maven-plugin/src/it/sample/src/izpack/Licence.txt
  izpack-maven-plugin/src/it/sample/src/izpack/Readme.txt
  izpack-maven-plugin/src/it/sample/src/izpack/doc/doc.txt
  izpack-maven-plugin/src/it/sample/src/izpack/install.xml
  izpack-maven-plugin/src/it/sample/src/izpack/listener/install.xml
  izpack-maven-plugin/src/it/sample/src/izpack/listener/test1/ShouldNotSeenWith_ls.txt
  izpack-maven-plugin/src/it/sample/src/izpack/listener/test2/ShouldSeenWith_ls.txt
  izpack-maven-plugin/src/it/sample/src/izpack/script.bat
  izpack-maven-plugin/src/it/sample/src/izpack/src/IPValidator.java
  izpack-maven-plugin/src/it/sample/src/izpack/src/PWDEncryptor.java
  izpack-maven-plugin/src/it/sample/src/izpack/src/PWDValidator.java
  izpack-maven-plugin/src/it/sample/src/izpack/src/Scrambler.java
  izpack-maven-plugin/src/it/sample/src/izpack/src/myCompany/tools/install/listener/ChmodCompilerListener.java
  izpack-maven-plugin/src/it/sample/src/izpack/src/myCompany/tools/install/listener/ChmodInstallerListener.java
  izpack-maven-plugin/src/it/sample/src/main/java/com/company/izpack/panels/MyHelloPanel.java
  izpack-maven-plugin/src/it/settings.xml
Labels: izpack:build, cleanup

#733 [IZPACK-1707] Add long arguments support to Uninstaller (-console/-force)
  izpack-uninstaller/src/main/java/com/izforge/izpack/uninstaller/Uninstaller.java
Labels: enhancement

#744 [IZPACK-1698] Internationalization of CustomPanel is not available in SummaryPanel
  izpack-api/src/main/java/com/izforge/izpack/api/resource/Resources.java
  izpack-compiler/src/main/java/com/izforge/izpack/compiler/CompilerConfig.java
  izpack-installer/src/main/java/com/izforge/izpack/installer/container/provider/AbstractInstallDataProvider.java
  izpack-installer/src/main/java/com/izforge/izpack/installer/container/provider/AutomatedInstallDataProvider.java
  izpack-installer/src/main/java/com/izforge/izpack/installer/container/provider/ConsoleInstallDataProvider.java
  izpack-installer/src/main/java/com/izforge/izpack/installer/container/provider/GUIInstallDataProvider.java
  izpack-installer/src/main/java/com/izforge/izpack/installer/language/LanguageConsoleDialog.java
  izpack-installer/src/main/java/com/izforge/izpack/installer/language/LanguageDialog.java
  izpack-installer/src/test/java/com/izforge/izpack/installer/container/provider/AutomatedInstallDataProviderTest.java
  izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/UserInputPanel.java
  izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/Config.java
  izpack-panel/src/main/java/com/izforge/izpack/panels/userinput/field/UserInputPanelSpec.java
Labels: enhancement

#758 [IZPACK-1016] There is an extra space at top of every panel screen between 'Installation of' and 'ProgramName'
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/bgr.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/bra.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/cat.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/ces.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/chn.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/dan.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/deu.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/ell.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/eng.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/eus.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/fa.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/fin.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/fra.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/glg.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/hun.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/idn.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/ita.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/jpn.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/kor.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/msa.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/nld.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/nor.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/pol.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/prt.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/ron.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/rus.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/slk.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/spa.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/srp.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/swe.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/tur.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/twn.xml
  izpack-core/src/main/resources/com/izforge/izpack/bin/langpacks/installer/ukr.xml
Labels: cleanup

#749 [IZPACK-508] Execution of executable that contains "(" character fails
  izpack-panel/src/main/java/com/izforge/izpack/panels/process/ProcessPanelWorker.java
Labels: bug
